# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6ed2dfabc79386000f2cd626e08d806dcac09abb40a534a83ecea4f40d3c2922caa367d46afcf4fd52382a2329dcfb37f5cfa81c0f7b676ccc4baee1969be7

test:
  secret_key_base: 8c01bcb2c8c68cff513da41ef9f5e3d8c0abb844df4a897acae44746f4f0abfd8c49cb489826a28d475301fd04f9cb962eebe1946d7a14f4cde4e19b0d9a4823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
